version: '3'
services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example

    typesense:
        image: typesense/typesense:0.21.0.rc10
        ports:
            - 8108:8108
        environment:
            TYPESENSE_API_KEY: xyz
            TYPESENSE_DATA_DIR: /data/typesense
        volumes: 
            - ~/typesense-mongodb/typesense-data:/data/typesense
            