version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            source ~/.bash_profile
            sudo apt update
            nvm install node
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: yarn install
          command: npm install
      - save_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: docker-compose
          command: docker-compose up
      - run:
          name: npm test
          command: npm test -- --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

workflows:
  typesense_server_integration_tests:
    jobs:
      - test
